services:
  db:
    image: postgres:15
    container_name: mess_registration_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mess_registration
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  backend:
    image: muqeeth26832/mess-registration-backend:latest
    container_name: mess_registration_backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mess_registration
      DB_USER: postgres
      DB_PASSWORD: password
      DB_SSLMODE: disable
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production-make-it-long-and-random
      SYNC_INTERVAL_SECONDS: 30
      REDIS_DB: 0
      PORT: 8080
      MESS_API_KEY: mess-scanner-api-key-12345
      GOOGLE_CLIENT_ID: 198469300367-cp8pf2d1qa5p7trsvcgktlj2fcjrq2h8.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      FRONTEND_URL: https://mess.iith.dev
      BACKEND_URL: https://mess.iith.dev
    networks:
      - backend
      - frontend

  frontend:
    image: muqeeth26832/mess-registration-frontend:latest
    container_name: mess_registration_frontend
    depends_on:
      - backend
    environment:
      PUBLIC_API_URL: https://mess.iith.dev/api
      GOOGLE_CLIENT_ID: 198469300367-cp8pf2d1qa5p7trsvcgktlj2fcjrq2h8.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
    networks:
      - frontend

  redis:
    image: redis:7-alpine
    container_name: mess_registration_redis
    networks:
      - backend
  nginx:
    image: nginx:alpine
    container_name: mess_registration_nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend
      - frontend

volumes:
  postgres_data:

networks:
  frontend:
  backend:
