services:
  db:
    image: postgres:15
    container_name: mess_registration_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mess_registration
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  backend:
    # image: muqeeth26832/mess-registration-backend:latest
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: mess_registration_backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mess_registration
      DB_USER: postgres
      DB_PASSWORD: password
      DB_SSLMODE: disable
      REDIS_HOST: redis # instead of localhost
      REDIS_PORT: 6379

      # JWT Configuration
      JWT_SECRET: your-super-secret-jwt-key-change-in-production-make-it-long-and-random
      SYNC_INTERVAL_SECONDS: 30
      REDIS_DB: 0

      # Server Configuration
      PORT: 8080
      GIN_MODE: debug

      # API Keys
      MESS_API_KEY: mess-scanner-api-key-12345

      # OAuth Configuration
      #
      GOOGLE_CLIENT_ID: 1060092687139-6dq56kb1e5m7bopl7i7gr3grs0ih0hho.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
    networks:
      - backend
      - frontend

  frontend:
    image: muqeeth26832/mess-registration-frontend:latest
    # build:
    #   context: ./frontend
    #   dockerfile: ./Dockerfile
    container_name: mess_registration_frontend
    depends_on:
      - backend
    environment:
      GOOGLE_CLIENT_ID: 1060092687139-6dq56kb1e5m7bopl7i7gr3grs0ih0hho.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
    ports:
      - "3000:3000"
    networks:
      - frontend

  redis:
    image: redis:7-alpine
    container_name: mess_registration_redis
    # ports:
    #   - "6379:6379"
    networks:
      - backend
  nginx:
    image: nginx:alpine
    container_name: mess_registration_nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend
      - frontend

volumes:
  postgres_data:

networks:
  frontend:
  backend:
